version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      # Change directory for the install phase
      - cd TestAutomation
      - npm install
      - npx playwright install
      
  build:
    commands:
      # Change directory for the build phase
      - npx playwright test

  post_build:
    commands:
      # Change directory for the post_build phase
      - echo "Playwright tests finished."
      - echo "Checking for reports..."
      
reports:
  playwright-html-report:
    files:
      - 'playwright-report/**/*'
    base-directory: 'TestAutomation/playwright-report'
    discard-paths: no