version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - cd TestAutomation
      - npm install
      # This command installs the browser binaries without
      # attempting to use apt-get for system dependencies
      - npx playwright install
      
  build:
    commands:
      - cd TestAutomation
      - npx playwright test

  post_build:
    commands:
      - echo "Playwright tests finished."
      - cd TestAutomation
      - echo "Checking for reports..."
      
reports:
  playwright-html-report:
    files:
      - 'playwright-report/**/*'
    base-directory: 'TestAutomation/playwright-report'
    discard-paths: no