version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 22
        commands:
            - echo "Installing Node.js version 22 ..."
            - cd TestAutomation
            - npm ci
            - npx playwright install --with-deps

    build:
        commands:
            - cd cdk1
            - 'echo "Current dir: $(pwd)"'
            - npm ci
            - npm run build
            - npx cdk synth
    post_build:
        commands:
            - echo "Running Playwright tests"
