pipeline {
  agent any

  parameters {
    choice(
        name: 'ENV',
        choices: ['dev', 'test', 'stg'],  // List your envs here
        description: 'Select the environment to run Playwright tests against'
    )
    booleanParam(
            name: 'DEPLOY_CDK',
            defaultValue: false,
            description: 'Deploy CDK stack before running tests'
    )
  }

  stages {
    stage('Echo Env File') {
      steps {
        echo "Selected env: ${params.ENV_FILE}"
      }
    }


    stage('Check AWS CLI Execution') {
          steps {
              script {
                  // Use withCredentials to bind the stored AWS credentials to environment variables
                  withCredentials([
                      [$class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'david-shin-iam-user-cred',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']
                  ]) {
                      // The AWS CLI automatically uses these environment variables
                      // to authenticate.
                      // We run a simple command to list S3 buckets.
                      sh 'aws s3 ls'
                      
                      // We can also check the identity of the user
                      sh 'aws sts get-caller-identity'
                  }
              }
          }
    }

    stage('Deploy CDK Stack (Optional)') {
        when {
            expression { return params.DEPLOY_CDK }
        }
        steps {
            script {
                withAWS(credentials: 'david-shin-iam-user-cred', region: "${AWS_REGION}") {
                    dir('cdk') {
                        sh 'npm ci'
                    }
                }
            }
        }
    }
    

    stage('Install deps') {
        steps {
          dir('TestAutomation') {
              sh 'npm ci'
          }
        }
    }

    stage('Run Playwright Tests') {
        steps {
            dir('TestAutomation') {
                sh "ENV=${params.ENV} npx playwright test"
            }
        }
    }
  }
}