pipeline {
  agent any

  parameters {
    choice(
        name: 'ENV',
        choices: ['dev', 'test', 'stg'],  // List your envs here
        description: 'Select the environment to run Playwright tests against'
    )
    booleanParam(
            name: 'DEPLOY_CDK',
            defaultValue: false,
            description: 'Deploy CDK stack before running tests'
    )
  }

  environment {
      AWS_REGION = "ap-southeast-2"  // Change to your region
  }

  stages {

    stage('Echo Env File') {
      steps {
        echo "Selected env: ${params.ENV_FILE}"
      }
    }


    stage('Synthesize Stack') {
        steps {
            script{
               withAWS(credentials: 'david-shin-iam-user-cred', region: "${AWS_REGION}") {
                    dir('TestAutomation/cdk') {
                        sh 'npm ci'
                        sh 'npm run synth'
                    }
              }
            }

        }
    }

    stage('Bootstrap CDK (Optional)') {
        when {
            expression { return params.DEPLOY_CDK }
        }
        steps {
            script {
                withAWS(credentials: 'david-shin-iam-user-cred', region: "${AWS_REGION}") {
                        dir('TestAutomation/cdk') {
                            sh "npx cdk bootstrap aws://484907527321/${AWS_REGION}"
                        }
                    }
                }
            }
    }

    stage('Deploy CDK Stack (Optional)') {
        when {
            expression { return params.DEPLOY_CDK }
        }
        steps {
            script {
                withAWS(credentials: 'david-shin-iam-user-cred', region: "${AWS_REGION}") {
                    dir('TestAutomation/cdk') {
                        sh 'npm ci'
                        sh 'npm install aws-cdk --save-dev'
                        sh 'npx cdk deploy --require-approval never'
                    }
                }
            }
        }
    }


    // stage('Install deps') {
    //     steps {
    //       dir('TestAutomation') {
    //           sh 'npm ci'
    //       }
    //     }
    // }

    // stage('Run Playwright Tests') {
    //     steps {
    //         dir('TestAutomation') {
    //             sh "ENV=${params.ENV} npx playwright test"
    //         }
    //     }
    // }
  }
}
